In [1]:
import pandas as pd
import os
import datetime

# Lets first compile all data into single df

In [2]:
#df = pd.read_csv('./csse_covid_19_daily_reports_us/09-04-2020.csv')

#files = [file for file in os.listdir('./csse_covid_19_daily_reports_us')]

files=[f for f in os.listdir("./csse_covid_19_daily_reports_us") if f.endswith('.csv')]
all_data = pd.DataFrame()

for file in files:
    df = pd.read_csv('./csse_covid_19_daily_reports_us/' + file)
    all_data = pd.concat([all_data, df])
    


all_data.tail()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate
54,Washington,US,2020-04-25 06:32:46,47.4009,-121.4905,12977,722,NaN,12255.0,53.0,171.894387,160324.0,455.0,5.563690,84000053.0,USA,2123.664613,3.506203
55,West Virginia,US,2020-04-25 06:32:46,38.4912,-80.9545,1010,32,439.0,978.0,54.0,76.341763,29811.0,97.0,3.168317,84000054.0,USA,2253.291388,9.603960
56,Wisconsin,US,2020-04-25 06:32:46,44.2685,-89.6165,5356,263,NaN,5093.0,55.0,103.506165,59929.0,1353.0,4.910381,84000055.0,USA,1158.144318,25.261389
57,Wyoming,US,2020-04-25 06:32:46,42.7560,-107.3025,473,7,321.0,466.0,56.0,95.125090,8045.0,54.0,1.479915,84000056.0,USA,1617.930979,11.416490
58,Recovered,US,2020-04-25 06:32:46,NaN,NaN,0,0,99079.0,-99079.0,NaN,NaN,NaN,NaN,NaN,84070001.0,USA,NaN,NaN

## Combined all files in a dir into one csv file. Then, filtered out my state.

In [4]:
co_filtered = all_data[all_data['Province_State'] == 'Colorado']

In [10]:
co_filtered.to_csv('co_filtered.csv')

In [11]:
co_filtered.head()

,Province_State,Country_Region,Last_Update,Lat,Long_,Confirmed,Deaths,Recovered,Active,FIPS,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,UID,ISO3,Testing_Rate,Hospitalization_Rate
6,Colorado,US,2020-06-08 03:33:42,39.0598,-105.3111,27987,1527,4074.0,22386.0,8.0,485.992065,213014.0,4480.0,5.456105,84000008.0,USA,3698.971441,16.007432
6,Colorado,US,2020-06-07 03:53:50,39.0598,-105.3111,27834,1527,4055.0,22252.0,8.0,483.335232,208277.0,4472.0,5.486096,84000008.0,USA,3616.713807,16.066681
6,Colorado,US,2020-08-21 04:30:30,39.0598,-105.3111,54211,1903,5759.0,46549.0,8.0,941.369773,895207.0,6784.0,3.510358,84000008.0,USA,15545.199502,12.514065
6,Colorado,US,2020-08-22 04:30:29,39.0598,-105.3111,54211,1910,5759.0,46542.0,8.0,941.369773,906693.0,6797.0,3.510358,84000008.0,USA,15744.652993,12.538046
6,Colorado,US,2020-07-06 04:34:10,39.0598,-105.3111,34048,1701,4568.0,27779.0,8.0,591.240856,350717.0,5550.0,4.995888,84000008.0,USA,6090.173260,16.300517

## Combined all files in a dir into one csv file. Then, filtered out my state.

In [12]:
del co_filtered['Long_']
del co_filtered['Lat']
del co_filtered['UID']
del co_filtered['FIPS']

#### Deleted longtitude and latitude..^

In [13]:
co_filtered.head()

,Province_State,Country_Region,Last_Update,Confirmed,Deaths,Recovered,Active,Incident_Rate,People_Tested,People_Hospitalized,Mortality_Rate,ISO3,Testing_Rate,Hospitalization_Rate
6,Colorado,US,2020-06-08 03:33:42,27987,1527,4074.0,22386.0,485.992065,213014.0,4480.0,5.456105,USA,3698.971441,16.007432
6,Colorado,US,2020-06-07 03:53:50,27834,1527,4055.0,22252.0,483.335232,208277.0,4472.0,5.486096,USA,3616.713807,16.066681
6,Colorado,US,2020-08-21 04:30:30,54211,1903,5759.0,46549.0,941.369773,895207.0,6784.0,3.510358,USA,15545.199502,12.514065
6,Colorado,US,2020-08-22 04:30:29,54211,1910,5759.0,46542.0,941.369773,906693.0,6797.0,3.510358,USA,15744.652993,12.538046
6,Colorado,US,2020-07-06 04:34:10,34048,1701,4568.0,27779.0,591.240856,350717.0,5550.0,4.995888,USA,6090.173260,16.300517

In [15]:
co_filtered.dtypes

Province_State                  object
Country_Region                  object
Last_Update             datetime64[ns]
Confirmed                        int64
Deaths                           int64
Recovered                      float64
Active                         float64
Incident_Rate                  float64
People_Tested                  float64
People_Hospitalized            float64
Mortality_Rate                 float64
ISO3                            object
Testing_Rate                   float64
Hospitalization_Rate           float64
dtype: object

In [19]:
#co_filtered['Last_Update'] = pd.to_datetime(co_filtered['Last_Update'])

In [20]:
#co_filtered['Month'] = co_filtered['Last_Update'].dt.month

### Grouped by state ^

### Removed territories leaving only states^

# Now lets visualize data

In [ ]:
all_data.head()

In [ ]:
import matplotlib.pyplot as plt

states = [state for state, df in all_data.groupby('State')]

plt.bar(states, results['Confirmed'])
plt.xlabel('States', size = 15)
plt.ylabel('Confirmed Cases (in )', size = 15)
plt.title('Covid-19 Cases per State', size = 15)
plt.xticks(size = 9, rotation= 85)
plt.yticks(size = 10)



plt.grid()
plt.show()